const tData = [
  {
    id: 1,
    name: "Patreon Membership",
    value: "250.00",
    date: "20 May 2020",
    currency: "$",
    type: "Subcribe",
  },
  {
    id: 2,
    name: "Patreon Membership",
    value: "250.00",
    date: "20 May 2020",
    currency: "$",
    type: "Subcribe",
  },
  {
    id: 3,
    name: "Patreon Membership",
    value: "250.00",
    date: "20 May 2020",
    currency: "$",
    type: "Subcribe",
  },
  {
    id: 4,
    name: "Patreon Membership",
    value: "250.00",
    date: "20 May 2020",
    currency: "$",
    type: "Subcribe",
  },
  {
    id: 5,
    name: "Patreon Membership",
    value: "250.00",
    date: "20 May 2020",
    currency: "$",
    type: "Subcribe",
  },
  {
    id: 6,
    name: "Patreon Membership",
    value: "250.00",
    date: "20 May 2020",
    currency: "$",
    type: "Subcribe",
  },
  {
    id: 7,
    name: "Patreon Membership",
    value: "250.00",
    date: "20 May 2020",
    currency: "$",
    type: "Subcribe",
  },
];
export default tData;
